theme: jekyll-theme-minimal
title: "TrISMA: Introduction and applications"
description: "24 August 2018, 10:30 - 12:30 | Room S226, John Woolley Building A20, The University of Sydney"
logo: "https://digital-methods-sydney.github.io/ws-201806/img/digital-methods-logo.png"